---
- name: Descargar WordPress
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz

- name: Extraer WordPress
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /var/www/html
    remote_src: yes

- name: Configurar permisos
  file:
    path: /var/www/html/wordpress
    owner: www-data
    group: www-data
    mode: "0755"
    recurse: yes

